image: node:18.14

options:
  max-time: 30

clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly

definitions:
  services:
    docker: 
      memory: 6000
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &lint-test-build
        name: Lint, tests and build
        caches:
          - node
          - sonar
          - docker # used by sonar pipes
        size: 2x # needed for additional memory requirements
        script:
          - npm ci
          - npm run ci:lint
          - npm run coverage
          - npm run audit
          - pipe: sonarsource/sonarcloud-scan:1.4.0
            variables:
              SONAR_SCANNER_OPTS: -Xmx4G
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.6

pipelines:
  pull-requests:
    '**':
      - step: *lint-test-build
  branches:
    master:
      - step: *lint-test-build