image: node:14.20.0

pipelines:
  default:
    - step:
        name: npm audit
        script:
          - npm ci
          - npm run audit
        caches:
          - node
    - step:
        name: Unit tests & coverage
        script:
          - npm ci
          - npm run coverage -- --ci
        caches:
          - node
    - step:
        name: Lint
        script:
          - npm ci
          - npm run lint
        caches:
          - node