image: node:14.20.0

pipelines:
  default:
    - step:
        name: npm install
        script:
          - npm ci
        caches:
          - node
    - parallel:
        - step:
            name: npm audit
            script:
              - npm run audit
            caches:
              - node
        - step:
            name: Unit tests & coverage
            script:
              - npm run coverage -- --ci
            caches:
              - node
        - step:
            name: Lint
            script:
              - npm run lint
            caches:
              - node