image: node:18.14.2

definitions:
  steps:
    - step: &lint-test-build
        name: Lint, tests and build
        caches:
          - node
        script:
          - npm ci
          - npm run lint
          - npm run coverage -- --ci
          - npm run audit
          - cd demo
          - npm ci
          - npm run generate

pipelines:
  pull-requests:
    '**':
      - step: *lint-test-build
  branches:
    master:
      - step: *lint-test-build