image: node:18.12.1

definitions:
  steps:
    - step: &lint-test-build
        name: Lint, tests and build
        caches:
          - node
        script:
          - npm ci
          - npm run ci:lint
          - npm run coverage
          - npm run audit

pipelines:
  pull-requests:
    '**':
      - step: *lint-test-build
  branches:
    master:
      - step: *lint-test-build