image: node:20.11.0

options:
  max-time: 10

definitions:
  services:
    docker:
      memory: 6000
  caches:
    sonar: ~/.sonar/cache
    pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store
  steps:
    - step: &lint-test-build
        name: Lint, tests and build
        caches:
          - pnpm
          - sonar
          - docker # used by sonar pipes
        size: 2x # needed for additional memory requirements
        clone:
          depth: full # SonarCloud scanner needs the full history to assign issues properly
        script:
          - corepack enable
          - corepack prepare pnpm@latest-9 --activate
          - pnpm install
          - pnpm run ci:lint-format
          - pnpm run type-check
          # - pnpm run coverage # TODO not available yet
          - pnpm run build:packages
          # - pnpm run audit
          - pipe: sonarsource/sonarcloud-scan:2.0.0
            variables:
              SONAR_SCANNER_OPTS: -Xmx4G
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
        artifacts:
          - demo/dist/**
    - step: &deploy-npm
        name: Deploy packages to npm
        caches:
          - pnpm
        trigger: manual
        deployment: production
        script:
          - pnpm run publish
          - git push --follow-tags
    - step: &deploy-demo
        name: Deploy demo to GitHub Pages
        caches:
          - pnpm
        deployment: production
        script:
          # TODO do we need to re-build the demo? Do we get it from the artifacts?
          # https://support.atlassian.com/bitbucket-cloud/docs/push-back-to-your-repository/#Configuring-an-alternate-Git-client
          - git config --global http.${BITBUCKET_GIT_HTTP_ORIGIN}.proxy http://localhost:29418/
          - pnpm run deploy-demo # TODO not available yet

pipelines:
  pull-requests:
    "**":
      - step: *lint-test-build
      - step: *deploy-npm
  branches:
    master:
      - step: *lint-test-build
      - step: *deploy-demo
