packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  - "demo2"
  # demo app is not published but part of workspace, enable again when imports are resolved differently
  - "!demo"
