packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  - "demo"

catalog:
  "@floating-ui/vue": 1.1.8
  "@knime/kds-components": 0.0.8
  "@knime/kds-styles": 0.0.8
  "@knime/vue-headless-virtual-scroller": 0.1.3
  "@types/lodash-es": 4.17.12
  "@vitejs/plugin-vue": ^6.0.1
  "@vitest/coverage-v8": 3.2.4
  "@vue/test-utils": 2.4.6
  "@vueuse/components": ~13.8.0
  "@vueuse/core": ~13.8.0
  "@vueuse/shared": ~13.8.0
  consola: 3.4.2
  eslint: 9.38.0
  lodash-es: 4.17.21
  npm-run-all2: ^8.0.4
  globals: ^16.3.0
  postcss: 8.5.6
  prettier: 3.3.2
  stylelint: 16.23.0
  typescript: ^5.8.3
  vite: 7.1.11
  vite-plugin-dts: 4.5.4
  vite-plugin-css-injected-by-js: ^3.5.2
  vite-svg-loader: 5.1.0
  vitest: 3.2.4
  vue: ~3.5.18
  vue-tsc: 3.0.4

catalogs:
  peer:
    "@fontsource/roboto": "5.x"
    "@fontsource/roboto-mono": "5.x"
    consola: 3.x
    eslint: ">=9.38.0"
    prettier: 3.x
    stylelint: 16.x
    vue: ">=3.5.0"
  patch:
    v-calendar: "git+https://bitbucket.org/KNIME/v-calendar#048477f"

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@knime/*"
