packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  - "demo"

catalog:
  "@floating-ui/vue": 1.1.5
  "@knime/vue-headless-virtual-scroller": 0.1.2
  "@types/lodash-es": 4.17.12
  "@vitejs/plugin-vue": ^5.1.4
  "@vitest/coverage-v8": 2.1.9
  "@vue/test-utils": 2.4.6
  "@vueuse/components": ~10.11.1
  "@vueuse/core": ~10.11.1
  "@vueuse/shared": ~10.11.1
  consola: 3.2.3
  eslint: 9.22.0
  lodash-es: 4.17.21
  npm-run-all: ^4.1.5
  globals: ^16.0.0
  prettier: 3.3.2
  stylelint: 16.14.1
  typescript: ^5.4.5
  vite: 5.4.17
  vite-plugin-dts: 4.3.0
  vite-plugin-css-injected-by-js: ^3.5.1
  vite-svg-loader: 5.1.0
  vitest: 2.1.9
  vue: ~3.4.27
  vue-tsc: 2.2.0

catalogs:
  peer:
    consola: 3.x
    eslint: 9.x
    prettier: 3.x
    stylelint: 16.x
    vue: ">=3.4.0"
