import type { PropType, StyleValue } from "vue";
import { type Boundary } from "@floating-ui/vue";
import type { MenuItem } from "./MenuItems.vue";
declare const _default: import("vue").DefineComponent<{
    items: {
        type: PropType<MenuItem<any, any>[]>;
        required: true;
    };
    focusedItemIndex: {
        required: false;
        type: PropType<number | null>;
        default: null;
    };
    menuAriaLabel: {
        type: StringConstructor;
        required: true;
    };
    /**
     * Identifier for click handler. If left blank an id is generated.
     * NOTE: Autogenerated IDs might break SSR.
     */
    id: {
        default: () => string;
        type: StringConstructor;
    };
    /**
     * Maximum width in px of the menu
     */
    maxMenuWidth: {
        type: NumberConstructor;
        default: null;
    };
    positionRelativeToElement: {
        type: PropType<HTMLElement | null>;
        default: null;
    };
    /**
     * Element used to detect when the MenuItem is near the edges of a clipping parent.
     * This will then be used to automatically position opened floating submenus accordingly.
     *
     * Defaults to the document's body
     */
    clippingBoundary: {
        type: PropType<Boundary>;
        default: HTMLElement;
    };
}, {
    listContainerFloatingStyles: StyleValue;
    listContainer: import("vue").Ref<HTMLElement | null>;
    listItems: import("vue").Ref<(HTMLElement | {
        $el: HTMLElement;
    })[]>;
}, unknown, {
    useMaxMenuWidth(): boolean;
    enabledItemsIndices(): number[];
}, {
    updateItem(el: HTMLElement, index: number): void;
    getEnabledListItems(): {
        element: HTMLLIElement;
        index: number;
        onClick: () => void;
    }[];
    scrollTo(element: HTMLLIElement): void;
    menuItemId(index: number): string;
    onPointerEnter(event: Event, item: MenuItem, index: number): void;
    onItemClick(event: Event, item: MenuItem, id?: string): void;
    emitItemFocused(): void;
}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, ("item-click" | "item-focused" | "item-hovered")[], "item-click" | "item-focused" | "item-hovered", import("vue").PublicProps, Readonly<import("vue").ExtractPropTypes<{
    items: {
        type: PropType<MenuItem<any, any>[]>;
        required: true;
    };
    focusedItemIndex: {
        required: false;
        type: PropType<number | null>;
        default: null;
    };
    menuAriaLabel: {
        type: StringConstructor;
        required: true;
    };
    /**
     * Identifier for click handler. If left blank an id is generated.
     * NOTE: Autogenerated IDs might break SSR.
     */
    id: {
        default: () => string;
        type: StringConstructor;
    };
    /**
     * Maximum width in px of the menu
     */
    maxMenuWidth: {
        type: NumberConstructor;
        default: null;
    };
    positionRelativeToElement: {
        type: PropType<HTMLElement | null>;
        default: null;
    };
    /**
     * Element used to detect when the MenuItem is near the edges of a clipping parent.
     * This will then be used to automatically position opened floating submenus accordingly.
     *
     * Defaults to the document's body
     */
    clippingBoundary: {
        type: PropType<Boundary>;
        default: HTMLElement;
    };
}>> & {
    "onItem-click"?: ((...args: any[]) => any) | undefined;
    "onItem-focused"?: ((...args: any[]) => any) | undefined;
    "onItem-hovered"?: ((...args: any[]) => any) | undefined;
}, {
    id: string;
    focusedItemIndex: number | null;
    maxMenuWidth: number;
    positionRelativeToElement: HTMLElement | null;
    clippingBoundary: Boundary;
}, {}>;
export default _default;
