/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type EmptyPayload = null;
export type NodeCreated_Base = NodeCreated_Common & NodeOrComponent;
export type NodeCreated_WithOptionalConnectedTo = NodeCreated_Common &
  NodeOrComponent & {
    connectedTo?: ConnectedTo_Basic;
  };
export type NodeCreated_WithOptionalConnectedToPorts = NodeCreated_Common &
  NodeOrComponent & {
    connectedTo?: ConnectedTo_WithPorts;
  };

export interface AnalyticsEventSchema {
  version: "v1.0";
  events: {
    kai_prompted: {
      kaiqa_button_: EmptyPayload;
      kaibuild_button_: EmptyPayload;
      qam_button_: KaiPromptedPayload;
    };
    session_started: {
      autotrigger: EmptyPayload;
    };
    session_ended: {
      session_tab_closed: EmptyPayload;
      autotrigger_timedout_: EmptyPayload;
      autotrigger_disconnect_: EmptyPayload;
    };
    session_interrupted: {
      session_tab: EmptyPayload;
    };
    session_resumed: {
      session_tab: EmptyPayload;
    };
    containernode_created: {
      canvas_ctxmenu_: ContainerNodeCreatedPayload;
      keyboard_shortcut_: ContainerNodeCreatedPayload;
    };
    hint_shown: {
      autotrigger: HintIdPayload;
    };
    hint_closed: {
      hint_button_: HintIdPayload;
    };
    configuration_completed: {
      nodedialog_button_apply: ConfigurationCompletedPayload;
      nodedialog_click_autoapply: ConfigurationCompletedPayload;
    };
    layouteditor_opened: {
      canvas_ctxmenu_openlayouteditor: EmptyPayload;
      keyboard_shortcut_openlayouteditor: EmptyPayload;
      wftoolbar_button_openlayouteditor: EmptyPayload;
    };
    annotation_created: {
      canvas_ctxmenu_newannotation: EmptyPayload;
      canvas_ctxmenu_kaiexplain: EmptyPayload;
    };
    workflow_saved: {
      wftoolbar_button_save: WorkflowSavedPayload;
      keyboard_shortcut_savewf: WorkflowSavedPayload;
    };
    connection_created: {
      port_dragdrop_fwd: ConnectionCreatedPayload;
      port_dragdrop_bwd: ConnectionCreatedPayload;
      keyboard_shortcut_connectnodes: EmptyPayload;
      keyboard_shortcut_connectflowvar: EmptyPayload;
      canvas_ctxmenu_connectnodes: EmptyPayload;
      canvas_ctxmenu_connectflowvar: EmptyPayload;
    };
    node_created: {
      noderepo_dragdrop_: NodeCreated_Base;
      noderepo_doubleclick_: NodeCreated_WithOptionalConnectedTo;
      noderepo_keyboard_enter: NodeCreated_WithOptionalConnectedTo;
      canvas_dragdrop_datafile: NodeCreated_Base;
      floatingcanvastools_button_addnodebyfile: NodeCreated_Base;
      explorer_dragdrop_: NodeCreated_Base;
      qam_click_: NodeCreated_WithOptionalConnectedToPorts;
      qam_keyboard_enter: NodeCreated_WithOptionalConnectedToPorts;
      kaiqa_dragdrop_: NodeCreated_Base;
      kaiqa_keyboard_enter: NodeCreated_Base;
    };
    qam_opened: {
      port_dragdrop_fwd: QAMOpened_Payload;
      port_dragdrop_bwd: QAMOpened_Payload;
      canvas_doubleclick_: EmptyPayload;
      keyboard_shortcut_: QAMOpened_PartialPayload;
      canvas_ctxmenu_quickaddnode: EmptyPayload;
    };
    node_searched: {
      noderepo_type_: SearchPayload;
      qam_type_: SearchPayload;
    };
    sidepanel_opened: {
      sidepanel_click_info: EmptyPayload;
      sidepanel_click_noderepo: EmptyPayload;
      sidepanel_click_explorer: EmptyPayload;
      sidepanel_click_kai: EmptyPayload;
      sidepanel_click_monitor: EmptyPayload;
      wftoolbar_dropdownmenu_versionhistory: EmptyPayload;
    };
    action_undone: {
      wftoolbar_button_: EmptyPayload;
      keyboard_shortcut_: EmptyPayload;
    };
    action_redone: {
      wftoolbar_button_: EmptyPayload;
      keyboard_shortcut_: EmptyPayload;
    };
    version_created: {
      versionhistorypanel_button_: EmptyPayload;
    };
  };
}
export interface KaiPromptedPayload {
  nodeFactoryId?: string;
  nodeType?: "node" | "component" | "metanode";
}
export interface ContainerNodeCreatedPayload {
  nodeType: "component" | "metanode";
  childrenNodes: {
    nodeType: "component" | "metanode" | "node";
    nodeFactoryId?: string;
  }[];
}
export interface HintIdPayload {
  hintId: string;
}
export interface ConfigurationCompletedPayload {
  nodeFactoryId?: string;
  state: "success" | "failed_invalid_setting";
}
export interface WorkflowSavedPayload {
  isAutosyncEnabled: boolean;
}
export interface ConnectionCreatedPayload {
  fromNode: ConnectionCreated_NodePayload;
  toNode: ConnectionCreated_NodePayload;
}
export interface ConnectionCreated_NodePayload {
  nodeType: "node" | "component" | "metanode";
  nodePortIndex: number;
  nodePortId: string;
  nodeFactoryId?: string;
}
export interface NodeCreated_Common {
  nodeType: "node" | "component";
}
export interface NodeOrComponent {
  nodeFactoryId?: string;
  nodeHubId?: string;
}
export interface ConnectedTo_Basic {
  nodeType: "node" | "component" | "metanode";
  nodeFactoryId: string;
}
export interface ConnectedTo_WithPorts {
  nodeType: "node" | "component" | "metanode";
  nodeFactoryId: string;
  nodePortIndex?: number;
  nodePortId?: string;
  direction: "forward" | "backward";
}
export interface QAMOpened_Payload {
  connectedTo: ConnectedTo_WithPorts;
}
export interface QAMOpened_PartialPayload {
  connectedTo?: ConnectedTo_WithPorts;
}
export interface SearchPayload {
  repoType: "node" | "component";
  keyword: string;
}
