/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type EmptyPayload = null;
export type NodeCreated_Base = NodeCreated_Common & NodeOrComponent;
export type NodeCreated_WithOptionalConnectedTo = NodeCreated_Common &
  NodeOrComponent & {
    connectedTo?: ConnectedTo_Basic;
  };
export type NodeCreated_WithOptionalConnectedToPorts = NodeCreated_Common &
  NodeOrComponent & {
    connectedTo?: ConnectedTo_WithPorts;
  };

export interface AnalyticsEvents {
  version: "v1";
  events: {
    "kai_prompted::kaiqa_button_prompt": EmptyPayload;
    "kai_prompted::kaibuild_button_prompt": EmptyPayload;
    "kai_prompted::qam_button_prompt": KaiPromptedPayload;
    "layouteditor_opened::canvas_ctxmenu_openlayouteditor": EmptyPayload;
    "layouteditor_opened::keyboard_shortcut_openlayouteditor": EmptyPayload;
    "layouteditor_opened::wftoolbar_button_openlayouteditor": EmptyPayload;
    "annotation_created::canvas_ctxmenu_newannotation": EmptyPayload;
    "annotation_created::canvas_ctxmenu_kaiexplain": EmptyPayload;
    "workflow_saved::wftoolbar_button_save": WorkflowSavedPayload;
    "workflow_saved::keyboard_shortcut_savewf": WorkflowSavedPayload;
    "connection_created::port_dragdrop_fwd": ConnectionCreatedPayload;
    "connection_created::port_dragdrop_bwd": ConnectionCreatedPayload;
    "connection_created::keyboard_shortcut_connectnodes": EmptyPayload;
    "connection_created::keyboard_shortcut_connectflowvar": EmptyPayload;
    "connection_created::canvas_ctxmenu_connectnodes": EmptyPayload;
    "connection_created::canvas_ctxmenu_connectflowvar": EmptyPayload;
    "node_created::noderepo_dragdrop_": NodeCreated_Base;
    "node_created::noderepo_doubleclick_": NodeCreated_WithOptionalConnectedTo;
    "node_created::noderepo_keyboard_enter": NodeCreated_WithOptionalConnectedTo;
    "node_created::explorer_dragdrop_": NodeCreated_Base;
    "node_created::qam_click_": NodeCreated_WithOptionalConnectedToPorts;
    "node_created::qam_keyboard_enter": NodeCreated_WithOptionalConnectedToPorts;
    "node_created::kaiqa_dragdrop_": NodeCreated_Base;
    "node_created::kaiqa_keyboard_enter": NodeCreated_Base;
    "qam_opened::port_dragdrop_fwd": QAMOpened_Payload;
    "qam_opened::port_dragdrop_bwd": QAMOpened_Payload;
    "qam_opened::canvas_doubleclick_": EmptyPayload;
    "qam_opened::keyboard_shortcut_": QAMOpened_PartialPayload;
    "qam_opened::canvas_ctxmenu_quickaddnode": EmptyPayload;
    "node_searched::noderepo_type_": SearchPayload;
    "node_searched::qam_type_": SearchPayload;
    "sidepanel_opened::sidepanel_click_info": EmptyPayload;
    "sidepanel_opened::sidepanel_click_noderepo": EmptyPayload;
    "sidepanel_opened::sidepanel_click_explorer": EmptyPayload;
    "sidepanel_opened::sidepanel_click_kai": EmptyPayload;
    "sidepanel_opened::sidepanel_click_monitor": EmptyPayload;
    "sidepanel_opened::wftoolbar_dropdownmenu_versionhistory": EmptyPayload;
    "action_undone::wftoolbar_button_": EmptyPayload;
    "action_undone::keyboard_shortcut_": EmptyPayload;
    "action_redone::wftoolbar_button_": EmptyPayload;
    "action_redone::keyboard_shortcut_": EmptyPayload;
  };
}
export interface KaiPromptedPayload {
  nodeFactoryId?: string;
  nodeType?: string;
}
export interface WorkflowSavedPayload {
  isAutosyncEnabled: boolean;
}
export interface ConnectionCreatedPayload {
  fromNode: ConnectionCreated_NodePayload;
  toNode: ConnectionCreated_NodePayload;
}
export interface ConnectionCreated_NodePayload {
  type: string;
  portIndex: number;
  portId: string;
  factoryId?: string;
}
export interface NodeCreated_Common {
  nodeType: string;
}
export interface NodeOrComponent {
  nodeFactoryId?: string;
  nodeHubId?: string;
}
export interface ConnectedTo_Basic {
  nodeType: string;
  nodeFactoryId: string;
}
export interface ConnectedTo_WithPorts {
  nodeType: string;
  nodeFactoryId: string;
  nodePortIndex?: number;
  nodePortId?: string;
}
export interface QAMOpened_Payload {
  connectedTo: ConnectedTo_WithPorts;
}
export interface QAMOpened_PartialPayload {
  connectedTo?: ConnectedTo_WithPorts;
}
export interface SearchPayload {
  repoType: "node" | "component";
  keyword: string;
}
