export const inputFormats = {
  columnSelect: "columnSelection",
  dropDown: "dropDown",
  radio: "radio",
  valueSwitch: "valueSwitch",
  checkbox: "checkbox",
  checkboxes: "checkboxes",
  integer: "integer",
  number: "number",
  columnFilter: "columnFilter",
  nameFilter: "nameFilter",
  richTextInput: "richTextInput",
  twinList: "twinList",
  comboBox: "comboBox",
  sortList: "sortList",
  button: "button",
  simpleButton: "simpleButton",
  textArea: "textArea",
  credentials: "credentials",
  legacyCredentials: "legacyCredentials",
  localFileChooser: "localFileChooser",
  fileChooser: "fileChooser",
};
